INSERT INTO `kommunalvalg`.`admin` (`admin_id`, `admin_name`, `admin_password`) VALUES ('1', 'admin', '123');

INSERT INTO `kommunalvalg`.`parti` (`parti_id`, `parti_name`) VALUES ('1', 'A. Socialdemokratiet');
INSERT INTO `kommunalvalg`.`parti` (`parti_id`, `parti_name`) VALUES ('2', 'C. Det Konservative Folkeparti');
INSERT INTO `kommunalvalg`.`parti` (`parti_id`, `parti_name`) VALUES ('3', 'F. SF - Socialistisk Folkeparti');
INSERT INTO `kommunalvalg`.`parti` (`parti_id`, `parti_name`) VALUES ('4', 'O. Dansk Folkeparti');
INSERT INTO `kommunalvalg`.`parti` (`parti_id`, `parti_name`) VALUES ('5', 'V. Venstre, Danmarks Liberale Parti');
INSERT INTO `kommunalvalg`.`parti` (`parti_id`, `parti_name`) VALUES ('6', 'Ø. Enhedslisten - De Rød-Grønne');

INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('1', 'Marcel Meijer', '1');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('2', 'Michael Kristensen', '1');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('3', 'Helle Hansen', '1');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('4', 'Karina Knobelauch', '1');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('5', 'Stefan Hafstein Wolffbrandt', '1');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('6', 'Robert V. Rasmussen', '1');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('7', 'Pia Ramsing', '1');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('8', 'Anders Baun Sørensen', '1');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('9', 'Per Urban Olsen', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('10', 'Peter Askjær', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('11', 'Martin Sørensen', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('12', 'Louise Bramstorp', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('13', 'Sigfred Jensen', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('14', 'Jørn C. Nissen', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('15', 'Morten Ø. Kristensen', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('16', 'Susanne Andersen', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('17', 'Iulian V. Paiu', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('18', 'Per Hingel', '2');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('19', 'Ulla Holm', '3');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('20', 'Kjeld Bønkel', '3');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('21', 'Anne Grethe Olsen', '3');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('22', 'Lone Krag', '3');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('23', 'Børge S. Buur', '3');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('24', 'Per Mortensen', '4');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('25', 'Søren Wiese', '5');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('26', 'Anita Elgaard Højholt Olesen', '5');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('27', 'Carsten Bruun', '5');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('28', 'Mogens Exner', '5');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('29', 'Anja Guldborg', '5');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('30', 'Klaus Holdorf', '5');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('31', 'Katrine Høegh Mc Quaid', '6');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('32', 'Jette M. Søgaard', '6');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('33', 'Søren Caspersen', '6');
INSERT INTO `kommunalvalg`.`kandidat` (`kandidat_id`, `kandidat_name`, `parti_id`) VALUES ('34', 'Pia Birkmand', '6');

UPDATE `kommunalvalg`.`parti` SET `parti_votes` = '829' WHERE (`parti_id` = '1');
UPDATE `kommunalvalg`.`parti` SET `parti_votes` = '595' WHERE (`parti_id` = '2');
UPDATE `kommunalvalg`.`parti` SET `parti_votes` = '335' WHERE (`parti_id` = '3');
UPDATE `kommunalvalg`.`parti` SET `parti_votes` = '27' WHERE (`parti_id` = '4');
UPDATE `kommunalvalg`.`parti` SET `parti_votes` = '654' WHERE (`parti_id` = '5');
UPDATE `kommunalvalg`.`parti` SET `parti_votes` = '128' WHERE (`parti_id` = '6');
